apiVersion: v1
kind: Service
metadata:
    name: "k8sbi01"
    labels:
        app: "k8sbi01"
spec:
    type: LoadBalancer
    ports:
    - port: 9090
      targetPort: http
      protocol: TCP
      name: http
    selector:
        app: "k8sbi01"