on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: a0101.azurecr.io
        username: ${{ secrets.acr_a0101_username }}
        password: ${{ secrets.acr_a0101_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/TV" -f  "liron-tovana-fs" -t a0101.azurecr.io/k8sbi01:${{ github.sha }}
        docker push a0101.azurecr.io/k8sbi01:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_k8sbi01_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep k8sbi011a23 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace k8sbi011a23`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: k8sbi011a23
        container-registry-url: a0101.azurecr.io
        container-registry-username: ${{ secrets.acr_a0101_username }}
        container-registry-password: ${{ secrets.acr_a0101_password }}
        secret-name: k8sbi01dockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: k8sbi011a23
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          a0101.azurecr.io/k8sbi01:${{ github.sha }}
        imagepullsecrets: |
          k8sbi01dockerauth