on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n a0101 -g a0101b300-rg --location "Central US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n a0101 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n a0101 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n a0101 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: a0101.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/liron-tovana-fs/TV" -f  "liron-tovana-fs/TV" -t a0101.azurecr.io/k8sbi01:${{ github.sha }}
        docker push a0101.azurecr.io/k8sbi01:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_k8sbi01_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep k8sbi01314e | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace k8sbi01314e`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: k8sbi01314e
        container-registry-url: a0101.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: k8sbi01dockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: k8sbi01314e
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          a0101.azurecr.io/k8sbi01:${{ github.sha }}
        imagepullsecrets: |
          k8sbi01dockerauth